/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.Jugador;
import civitas.tituloPropiedad;
import java.util.ArrayList;

/**
 *
 * @author arturo
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    Jugador jugador;
    
    private void rellenaPropiedades(ArrayList<tituloPropiedad> lista){
        propiedades.removeAll();
        
        for(tituloPropiedad t:lista){
            PropiedadPanel vistaPropiedad=new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            vistaPropiedad.setVisible(true);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        
        propiedades.repaint();
        propiedades.revalidate();
        
        repaint();
        revalidate();
    }
    
    void setJugador(Jugador jugador){
        this.jugador=jugador;
        Nombre.setText("Nombre: ");
        Saldo.setText("Saldo: ");
        Encarcelado.setText("Encarcelado: ");
        Espc.setText("Especulador: ");
        Casilla.setText("Número de casilla actual: ");
        Salvc.setText("Salvoconducto: ");
        nombre.setText(jugador.getNombre());
        saldo.setText(Float.toString(jugador.getSaldo()));
        encarcelado.setText(Boolean.toString(jugador.estaEncarcelado()));
        especulador.setText(Boolean.toString(jugador.esEspeculador()));
        casilla.setText(Integer.toString(jugador.getNumCasillaActual()));
        salvoconducto.setText(Boolean.toString(jugador.tieneSalvoconducto()));
        rellenaPropiedades(jugador.getPropiedades());
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Saldo = new javax.swing.JLabel();
        Encarcelado = new javax.swing.JLabel();
        Espc = new javax.swing.JLabel();
        Casilla = new javax.swing.JLabel();
        Salvc = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        encarcelado = new javax.swing.JTextField();
        especulador = new javax.swing.JTextField();
        casilla = new javax.swing.JTextField();
        salvoconducto = new javax.swing.JTextField();
        propiedades = new javax.swing.JPanel();

        Nombre.setText("Nombre");
        Nombre.setEnabled(false);

        Saldo.setText("Saldo");
        Saldo.setEnabled(false);

        Encarcelado.setText("Encarcelado");
        Encarcelado.setEnabled(false);

        Espc.setText("Especulador");
        Espc.setEnabled(false);

        Casilla.setText("Casilla");
        Casilla.setEnabled(false);

        Salvc.setText("Salvoconducto");
        Salvc.setEnabled(false);

        jLabel7.setText("Vista Jugador");
        jLabel7.setEnabled(false);

        nombre.setText("jTextField1");
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        saldo.setText("jTextField2");
        saldo.setEnabled(false);

        encarcelado.setText("jTextField3");
        encarcelado.setEnabled(false);

        especulador.setText("jTextField4");
        especulador.setEnabled(false);

        casilla.setText("jTextField5");
        casilla.setEnabled(false);

        salvoconducto.setText("jTextField6");
        salvoconducto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Casilla)
                            .addComponent(Espc)
                            .addComponent(Encarcelado)
                            .addComponent(Saldo)
                            .addComponent(Nombre)
                            .addComponent(Salvc))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salvoconducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Saldo)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Encarcelado)
                    .addComponent(encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Espc)
                    .addComponent(especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(casilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Casilla))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvc)
                    .addComponent(salvoconducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addComponent(propiedades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Casilla;
    private javax.swing.JLabel Encarcelado;
    private javax.swing.JLabel Espc;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Saldo;
    private javax.swing.JLabel Salvc;
    private javax.swing.JTextField casilla;
    private javax.swing.JTextField encarcelado;
    private javax.swing.JTextField especulador;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nombre;
    private javax.swing.JPanel propiedades;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField salvoconducto;
    // End of variables declaration//GEN-END:variables
}
